# Generated by Django 3.1.7 on 2021-03-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ani_image', models.ImageField(blank=True, upload_to='images/')),
                ('ani_name', models.CharField(max_length=200)),
                ('ani_description', models.TextField()),
            ],
        ),
    ]
