# Generated by Django 3.1.3 on 2020-11-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us_name', models.CharField(max_length=100)),
                ('us_email', models.CharField(max_length=100)),
                ('us_password', models.CharField(max_length=100)),
            ],
        ),
    ]
