# Generated by Django 3.1.3 on 2020-11-13 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ddapp.user_age'),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ddapp.user_country'),
        ),
    ]
