# Generated by Django 3.1.3 on 2020-11-13 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddapp', '0002_auto_20201114_0105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Country',
            new_name='User_height',
        ),
        migrations.RemoveField(
            model_name='user',
            name='height',
        ),
    ]
