# Generated by Django 3.1.3 on 2020-11-13 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddapp', '0004_remove_user_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='User_Age',
        ),
        migrations.DeleteModel(
            name='User_height',
        ),
    ]
