# Generated by Django 3.1.3 on 2020-11-13 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddapp', '0007_user_a_user_h'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='age',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ddapp.user_a'),
        ),
        migrations.AddField(
            model_name='user_info',
            name='height',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ddapp.user_h'),
        ),
    ]
