# Generated by Django 3.1.3 on 2020-11-17 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddapp', '0009_auto_20201117_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='countrypresident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ddapp.countryname')),
                ('president_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ddapp.president')),
            ],
        ),
    ]
